import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:google_fonts/google_fonts.dart';

// Firebase Options (Generated by CLI)
import 'firebase_options.dart';

// ViewModels (To be created)
import 'viewmodels/auth/login_viewmodel.dart';
import 'viewmodels/auth/register_viewmodel.dart';
import 'viewmodels/music/music_viewmodel.dart';
import 'viewmodels/quiz/quiz_viewmodel.dart';
import 'viewmodels/profile/profile_viewmodel.dart';

// Views (To be created)
import 'views/auth/auth_wrapper.dart';
import 'views/auth/login_screen.dart';
import 'views/auth/register_screen.dart';
import 'views/navigation/main_wrapper.dart';

void main() async {
  //ensure binding before calling native code
  WidgetsFlutterBinding.ensureInitialized();

  //initialize firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  //run app with MultiProvider
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => LoginViewModel()),
        ChangeNotifierProvider(create: (_) => RegisterViewModel()),
        ChangeNotifierProvider(create: (_) => MusicViewModel()),
        ChangeNotifierProvider(create: (_) => QuizViewModel()),

        ChangeNotifierProxyProvider2<
          LoginViewModel,
          RegisterViewModel,
          ProfileViewModel
        >(
          create: (_) => ProfileViewModel(),
          update: (context, login, register, profile) {
            return profile!..updateDependencies(dynamic, login, register);
          },
        ),
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: const Size(360, 690),
      minTextAdapt: true,
      splitScreenMode: true,
      builder: (context, child) {
        return MaterialApp(
          debugShowCheckedModeBanner: false,
          title: 'XMuse',

          //theme
          themeMode: ThemeMode.light,
          theme: ThemeData(
            useMaterial3: true,
            colorScheme: ColorScheme.fromSeed(
              seedColor: const Color(0xFFD32F2F),
              primary: const Color(0xFFD32F2F),
              brightness: Brightness.light,
              surface: const Color(0xFFF8F9FA),
            ),
            textTheme: GoogleFonts.interTextTheme(ThemeData.light().textTheme),
          ),

          home: const AuthWrapper(),

          routes: {
            '/login': (context) => const LoginScreen(),
            '/register': (context) => const RegisterScreen(),
            '/main-wrapper': (context) => const MainWrapper(),
          },
        );
      },
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold();
  }
}
